class InternalFunctionCalledError(Exception):
    pass

class FunctionNotFound(Exception):
    pass
